export const GET_ALL_ITEMS='GET_ALL_ITEMS';
export const GET_ALL_CATEGORY='GET_ALL_CATEGORY';
export const GET_ALL_SUB_CATEGORY='GET_ALL_SUB_CATEGORY';
export const GET_ALL_BRANDS='GET_ALL_BRANDS';
export const GET_ALL_MODEL ='GET_ALL_MODEL ';